export const detectPlatform = (input) => { try { const h = new URL(input).hostname.replace(/^www\./,''); if (h.endsWith('instagram.com')) return 'instagram'; if (h.endsWith('linkedin.com')) return 'linkedin'; if (h.endsWith('youtube.com') || h === 'youtu.be') return 'youtube'; } catch {} return 'unknown'; };
export function normalizeUrl(input){ const url=new URL(input); url.hash=''; url.hostname=url.hostname.toLowerCase().replace(/^m\./,'www.'); ['utm_source','utm_medium','utm_campaign','utm_term','utm_content','fbclid','gclid','si','feature'].forEach(p=>url.searchParams.delete(p)); if(url.hostname==='youtu.be'){const id=url.pathname.split('/').filter(Boolean)[0]; return `https://www.youtube.com/watch?v=${id}`;} if(url.hostname.endsWith('youtube.com')&&url.pathname==='/watch'){const id=url.searchParams.get('v'); return id?`https://www.youtube.com/watch?v=${id}`:url.toString();} url.pathname=url.pathname.replace(/\/$/,''); return url.toString(); }
export function stableId(prefix, source){ let hash=5381; for(let i=0;i<source.length;i++) hash=(hash*33)^source.charCodeAt(i); return `${prefix}_${(hash>>>0).toString(36)}`; }
const q=(doc,sel)=>doc.querySelector(sel)?.textContent?.trim()||undefined; const a=(doc,sel,n)=>doc.querySelector(sel)?.getAttribute(n)?.trim()||undefined;
export function extractCurrentPage(doc, href, signalType='manual_capture'){ const platform=detectPlatform(href); const base={platform,signalType,sourceUrl:href,canonicalUrl:safeNorm(a(doc,'link[rel="canonical"]','href')||href),title:a(doc,'meta[property="og:title"]','content')||doc.title||undefined,description:a(doc,'meta[property="og:description"]','content')||a(doc,'meta[name="description"]','content'),thumbnailUrl:a(doc,'meta[property="og:image"]','content'),mediaType:'unknown',extractionConfidence:.35,extractionWarnings:[]}; if(platform==='youtube'){const ch=doc.querySelector("ytd-video-owner-renderer a[href^='/@'], ytd-channel-name a, #owner a"); const title=q(doc,'h1 yt-formatted-string, h1.title, #title h1')||base.title?.replace(/ - YouTube$/,''); const transcript=[...doc.querySelectorAll('ytd-transcript-segment-renderer, .segment-text')].map(n=>n.textContent?.trim()).filter(Boolean).join('\n')||undefined; return {...base,signalType:signalType==='manual_capture'?'like':signalType,mediaType:'video',title,description:q(doc,'#description-inline-expander, ytd-text-inline-expander, #description')||base.description,transcript,creatorName:ch?.textContent?.trim()||undefined,creatorHandle:ch?.getAttribute('href')?.match(/@[^/?]+/)?.[0],creatorProfileUrl:ch?new URL(ch.getAttribute('href')||'', 'https://www.youtube.com').toString():undefined,extractionConfidence:transcript?.length?.valueOf()?0.95:.82,extractionWarnings:transcript?[]:['Transcript not visible; open transcript and recapture if needed.']}; }
 if(platform==='linkedin'){const article=doc.querySelector('div.feed-shared-update-v2, article, .feed-shared-update-v2')||doc.body; const author=article.querySelector('.update-components-actor__name, .feed-shared-actor__name, .hoverable-link-text'); const profile=article.querySelector("a[href*='/in/'], a[href*='/company/']"); const postText=article.querySelector('.update-components-text, .feed-shared-update-v2__description')?.textContent?.trim(); return {...base,signalType:signalType==='manual_capture'?'reaction':signalType,mediaType:'post',text:postText||base.description,title:base.title||(postText?`${author?.textContent?.trim()||'LinkedIn'} post`:undefined),creatorName:author?.textContent?.replace(/\s+/g,' ').trim(),creatorProfileUrl:profile?new URL(profile.getAttribute('href')||'', 'https://www.linkedin.com').toString():undefined,extractionConfidence:postText?.length?0.78:.42,extractionWarnings:postText?[]:['LinkedIn post text was not visible; expand or use permalink.']}; }
 if(platform==='instagram'){const article=doc.querySelector('article')||doc.body; const profile=article.querySelector("a[href^='/'][role='link'], header a[href^='/']"); const caption=article.querySelector('h1, ul li span, div[role="button"] span')?.textContent?.trim()||base.description; const handle=profile?.getAttribute('href')?.split('/').filter(Boolean)[0]; return {...base,signalType:signalType==='manual_capture'?'save':signalType,mediaType:/\/reel\//.test(href)?'reel':'post',text:caption,creatorName:handle,creatorHandle:handle?`@${handle}`:undefined,creatorProfileUrl:handle?`https://www.instagram.com/${handle}`:undefined,extractionConfidence:caption?.length?0.74:.38,extractionWarnings:caption?[]:['Instagram caption was not visible; open detail or expand caption.']}; }
 return {...base,extractionWarnings:['Unsupported platform; generic metadata captured only.']}; }
function safeNorm(u){try{return normalizeUrl(u)}catch{return u}}
export const toRawCapture=(e)=>({id:stableId('cap',e.canonicalUrl),...e,capturedAt:new Date().toISOString(),processingStatus:'queued'});
export function parseAiResponse(raw){ const json=raw.match(/```json\s*([\s\S]*?)```/i)?.[1]||raw.match(/\{[\s\S]*\}/)?.[0]||raw; const v=JSON.parse(json); const arr=x=>Array.isArray(x)?x.map(String).filter(Boolean):[]; const score=(x,f)=>typeof x==='number'?Math.max(0,Math.min(1,x)):f; return {shortSummary:String(v.shortSummary||'Captured item needs review.'),detailedSummary:String(v.detailedSummary||v.shortSummary||'No detailed summary available.'),keyIdeas:arr(v.keyIdeas),claims:arr(v.claims),examples:arr(v.examples),frameworks:arr(v.frameworks),toolsMentioned:arr(v.toolsMentioned),peopleMentioned:arr(v.peopleMentioned),companiesMentioned:arr(v.companiesMentioned),topics:arr(v.topics),subtopics:arr(v.subtopics),noveltyScore:score(v.noveltyScore,.5),usefulnessScore:score(v.usefulnessScore,.5),confidenceScore:score(v.confidenceScore,.55),sourceQualityScore:score(v.sourceQualityScore,.5)}; }
export function summarizeCapture(c){ const corpus=[c.title,c.text,c.description,c.transcript].filter(Boolean).join('\n'); const words=[...new Set((corpus.toLowerCase().match(/[a-z][a-z0-9-]{3,}/g)||[]).filter(w=>!STOP.has(w)))].slice(0,8).map(t=>t.replace(/(^|[-\s])\w/g,m=>m.toUpperCase())); const sentences=corpus.split(/(?<=[.!?])\s+/).filter(s=>s.trim().length>20); return {id:stableId('insight',c.id),rawCaptureId:c.id,shortSummary:sentences[0]?.slice(0,220)||`${c.platform} ${c.mediaType} from ${c.creatorName||c.creatorHandle||'unknown creator'}.`,detailedSummary:sentences.slice(0,4).join(' ')||corpus.slice(0,800)||'Captured metadata only; review source directly.',keyIdeas:words.slice(0,5).map(t=>`Explore ${t} in context of ${c.creatorName||c.platform}`),claims:sentences.filter(s=>/should|must|will|can|because|better|worse|avoid|use/i.test(s)).slice(0,5),examples:sentences.filter(s=>/for example|case|like|including/i.test(s)).slice(0,3),frameworks:words.filter(t=>/Strategy|Framework|System|Model|Loop|Process/i.test(t)),toolsMentioned:[...corpus.matchAll(/\b(OpenAI|Claude|Obsidian|Google Drive|LinkedIn|Instagram|YouTube|ChatGPT)\b/g)].map(m=>m[1]),peopleMentioned:[],companiesMentioned:[...corpus.matchAll(/\b(OpenAI|Google|Anthropic|Microsoft|Meta|LinkedIn|YouTube)\b/g)].map(m=>m[1]),topics:words.slice(0,4),subtopics:words.slice(4,8),noveltyScore:Math.min(.9,.35+words.length*.04),usefulnessScore:Math.min(.9,.4+sentences.length*.03),confidenceScore:corpus.length>80?.68:.42,sourceQualityScore:c.platform==='youtube'?.65:.55,createdAt:new Date().toISOString()}; }
const STOP=new Set('with from this that have been were your about into when what will they them then than just like post video more some only also such using used make made many very over because there their would could should through these those follow source captured instagram linkedin youtube'.split(' '));
export function clusterTopics(insights,captures){const m=new Map(); for(const i of insights) for(const t of (i.topics.length?i.topics:['Unsorted'])){const k=normTopic(t); m.set(k,[...(m.get(k)||[]),i]);} return [...m.entries()].map(([name,group])=>{const ids=group.map(g=>g.rawCaptureId); const ops=captures.filter(c=>ids.includes(c.id)).map(c=>c.creatorName||c.creatorHandle||'Unknown'); return {id:stableId('topic',name),name,summary:`${group.length} captured item${group.length===1?'':'s'} connect to ${name}. Recurring ideas: ${group.flatMap(g=>g.keyIdeas).slice(0,3).join('; ')||'review needed'}.`,relatedTopics:[...new Set(group.flatMap(g=>g.subtopics.concat(g.topics)).map(normTopic).filter(t=>t!==name))].slice(0,8),representativeCaptures:ids.slice(0,6),strongestOperators:[...new Set(ops)].slice(0,6),openQuestions:[`What evidence would weaken the strongest ${name} claim?`,`Which older sources inspired this idea?`],contradictoryViews:[`Search for rigorous critiques of ${name}.`],lastUpdatedAt:new Date().toISOString()};});}
export const normTopic=t=>t.trim().replace(/\s+/g,' ').replace(/(^|\s)\w/g,c=>c.toUpperCase());
export function deriveOperators(captures,insights){const m=new Map(); for(const c of captures){const k=c.creatorHandle||c.creatorName||`${c.platform}:unknown`; m.set(k,[...(m.get(k)||[]),c]);} return [...m.entries()].map(([k,items])=>{const first=items[0]; const itemInsights=insights.filter(i=>items.some(c=>c.id===i.rawCaptureId)); return {id:stableId('operator',`${first.platform}:${k}`),name:first.creatorName||first.creatorHandle||'Unknown operator',handle:first.creatorHandle,platform:first.platform,profileUrl:first.creatorProfileUrl,domains:[...new Set(itemInsights.flatMap(i=>i.topics))].slice(0,8),recurringThemes:[...new Set(itemInsights.flatMap(i=>i.keyIdeas))].slice(0,8),credibilityNotes:'Not yet independently verified; review original profile and external sources before relying on claims.',relatedOperators:[],capturedItemCount:items.length};});}
export function discoverForInsight(insight,operatorName){const topic=insight.topics[0]||insight.keyIdeas[0]||'captured idea'; const claim=insight.claims[0]||insight.shortSummary; return [['supports',`${operatorName||'creator'} ${topic}`,`More from ${operatorName||'the same operator'} on ${topic}`],['background',`${topic} foundational source examples`,`Foundational sources for ${topic}`],['contradicts',`${claim} critique evidence`,`Skeptical evidence about: ${claim.slice(0,80)}`],['adjacent',`${topic} practical case study`,`Practical examples adjacent to ${topic}`]].map(([rel,q,title])=>({id:stableId('research',`${insight.id}:${rel}:${q}`),relatedInsightId:insight.id,query:q,sourceTitle:title,sourceUrl:`https://www.google.com/search?q=${encodeURIComponent(q)}`,sourceType:'search',sourceSummary:`Seed research query for ${rel} material. Open this result, choose credible primary sources, and recapture useful items.`,supportsOrContradicts:rel,credibilityNotes:rel==='contradicts'?'Prefer rigorous skeptical sources, replication evidence, or experts with a clear counterargument.':'Prefer primary sources, named authors, and dated evidence.',capturedAt:new Date().toISOString()}));}
export function dedupeCaptures(captures){const seen=new Set(); return captures.filter(c=>{const k=c.canonicalUrl||c.sourceUrl; if(seen.has(k)) return false; seen.add(k); return true;});}
export function captureToMarkdown(capture,insight,research=[]){const title=safe(capture.title||insight?.shortSummary||`${capture.platform} capture`); const topics=insight?.topics||[]; const contradictions=research.filter(r=>r.supportsOrContradicts==='contradicts'); return `---\ntitle: "${esc(title)}"\nplatform: ${capture.platform}\nsignal_type: ${capture.signalType}\nsource_url: "${capture.sourceUrl}"\ncreator: "${esc(capture.creatorName||capture.creatorHandle||'Unknown')}"\ncaptured_at: ${capture.capturedAt}\ntags: [social-brain, ${capture.platform}, ${topics.map(tag).join(', ')}]\n---\n\n# ${title}\n\n## Source\n- Platform: ${capture.platform}\n- Signal: ${capture.signalType}\n- URL: ${capture.sourceUrl}\n- Creator: [[${safe(capture.creatorName||capture.creatorHandle||'Unknown operator')}]]\n- Captured: ${capture.capturedAt}\n\n## Summary\n${insight?.shortSummary||'Pending AI summary.'}\n\n${insight?.detailedSummary||''}\n\n## Key ideas\n${list((insight?.keyIdeas||[]).map(i=>`${i} ${topics[0]?`[[${safe(topics[0])}]]`:''}`))}\n\n## Claims\n${list(insight?.claims||[])}\n\n## Topics\n${list(topics.map(t=>`[[${safe(t)}]]`))}\n\n## Related operators\n${list([capture.creatorName||capture.creatorHandle].filter(Boolean).map(v=>`[[${safe(v)}]]`))}\n\n## Contradictory views\n${list(contradictions.map(r=>`[${r.sourceTitle}](${r.sourceUrl}) — ${r.sourceSummary}`))}\n\n## Suggested follow-up reading\n${list(research.filter(r=>r.supportsOrContradicts!=='contradicts').map(r=>`[${r.sourceTitle}](${r.sourceUrl}) — ${r.credibilityNotes}`))}\n\n## Backlinks\n${list(topics.map(t=>`[[${safe(t)}]]`))}\n`;}
export function buildExportedNotes(captures,insights,topics,operators,research){const by=new Map(insights.map(i=>[i.rawCaptureId,i])); const res=id=>research.filter(r=>r.relatedInsightId===id); return [...captures.map(c=>{const i=by.get(c.id); const path=`Social Brain/Captures/${cap(c.platform)}/${file(c.title||c.id)}.md`; return {id:stableId('note',path),noteType:'capture',destination:'obsidian',path,markdownContent:captureToMarkdown(c,i,res(i?.id)),syncStatus:'pending'};}),...topics.map(t=>({id:stableId('note',`topic:${t.id}`),noteType:'topic',destination:'obsidian',path:`Social Brain/Topics/${file(t.name)}.md`,markdownContent:`# ${safe(t.name)}\n\n${t.summary}\n`,syncStatus:'pending'})),...operators.map(o=>({id:stableId('note',`operator:${o.id}`),noteType:'operator',destination:'obsidian',path:`Social Brain/Operators/${file(o.name)}.md`,markdownContent:`# ${safe(o.name)}\n\n- Platform: ${o.platform}\n- Captured items: ${o.capturedItemCount}\n`,syncStatus:'pending'}))];}
function list(x){return x.length?x.map(i=>`- ${i}`).join('\n'):'- Pending review'} function safe(x){return String(x||'Untitled').replace(/[\n\r]+/g,' ').trim().slice(0,120)||'Untitled'} function esc(x){return safe(x).replace(/"/g,'\\"')} function tag(x){return x.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')} function file(x){return safe(x).replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,80)||'Untitled'} function cap(x){return x==='youtube'?'YouTube':x==='linkedin'?'LinkedIn':x==='instagram'?'Instagram':x.charAt(0).toUpperCase()+x.slice(1)}
export function processQueueMemory(captures){const processed=[],research=[]; for(const c of captures.filter(c=>c.processingStatus==='queued')){try{const i=summarizeCapture(c); processed.push(i); research.push(...discoverForInsight(i,c.creatorName||c.creatorHandle)); c.processingStatus='processed';}catch(e){c.processingStatus='failed'; c.extractionWarnings=[...(c.extractionWarnings||[]),String(e)];}} return {captures,processed,research,topics:clusterTopics(processed,captures),operators:deriveOperators(captures,processed)};}
export function buildZipBlobFromNotes(notes, kb){
  const files=Object.fromEntries(notes.map(n=>[n.path,n.markdownContent]));
  files['Social Brain/Raw Exports/knowledge-base.json']=JSON.stringify(kb,null,2);
  files['Social Brain/README.md']='# Social Brain export\n\nImport this folder into an Obsidian vault. Google Drive can be used as an optional backup target for this ZIP.\n';
  const chunks=[]; const central=[]; let offset=0;
  for(const [name,content] of Object.entries(files)){const data=utf8(content); const path=utf8(name); const crc=crc32(data); const local=header(0x04034b50, [20,0,0,0,0,0,crc,data.length,data.length,path.length,0]); chunks.push(local,path,data); central.push({name:path,crc,size:data.length,offset}); offset+=local.length+path.length+data.length;}
  const centralStart=offset;
  for(const f of central){const h=header(0x02014b50,[20,20,0,0,0,0,0,f.crc,f.size,f.size,f.name.length,0,0,0,0,0,f.offset]); chunks.push(h,f.name); offset+=h.length+f.name.length;}
  const end=header(0x06054b50,[0,0,central.length,central.length,offset-centralStart,centralStart,0]); chunks.push(end);
  return new Blob(chunks,{type:'application/zip'});
}
function utf8(s){return new TextEncoder().encode(s)}
function header(sig,vals){const lens=sig===0x04034b50?[2,2,2,2,2,2,4,4,4,2,2]:sig===0x02014b50?[2,2,2,2,2,2,2,4,4,4,2,2,2,2,2,4,4]:[2,2,2,2,4,4,2]; const b=new Uint8Array(4+lens.reduce((a,b)=>a+b,0)); const v=new DataView(b.buffer); v.setUint32(0,sig,true); let o=4; vals.forEach((val,i)=>{if(lens[i]===2)v.setUint16(o,val,true); else v.setUint32(o,val>>>0,true); o+=lens[i];}); return b;}
function crc32(data){let c=~0; for(const b of data){c^=b; for(let k=0;k<8;k++) c=(c>>>1)^(0xedb88320&-(c&1));} return ~c>>>0;}
