import type { Classification, Cluster, Opportunity, RawRecord } from "./types";

export const projects = [
  { id: "demo-ai-notes", name: "AI note-taking apps", category: "AI productivity", icp: "Founders, customer teams, PMMs", updatedAt: "2026-06-05" },
  { id: "demo-crm-reporting", name: "CRM reporting complaints", category: "RevOps / CRM", icp: "RevOps managers at B2B SaaS", updatedAt: "2026-06-05" },
  { id: "demo-pmm-tools", name: "PMM tools unmet demand", category: "Product marketing", icp: "Solo PMMs and PMM leaders", updatedAt: "2026-06-05" }
];

export const rawRecords: RawRecord[] = [
  { id: "crm-1", projectId: "demo-crm-reporting", source: "csv", sourceUrl: "https://example.com/g2/hubspot-reporting", author: "revops_lead", date: "2026-05-29", title: "HubSpot weekly reporting workaround", body: "I export HubSpot deals into Google Sheets every Friday because the native dashboards cannot show our renewal and expansion view. I'd pay for something that saved this manual reporting ritual.", product: "HubSpot", engagement: 18, ingestedAt: "2026-06-05T10:00:00Z" },
  { id: "crm-2", projectId: "demo-crm-reporting", source: "reddit", sourceUrl: "https://reddit.com/r/salesops/example", author: "ops_builder", date: "2026-05-31", title: "Any alternative to Salesforce reports?", body: "Any alternative to Salesforce reporting that doesn't require 3 admins and a pile of spreadsheet exports? Leadership wants pipeline by segment and it breaks every month.", product: "Salesforce", engagement: 42, ingestedAt: "2026-06-05T10:01:00Z" },
  { id: "crm-3", projectId: "demo-crm-reporting", source: "hacker_news", sourceUrl: "https://news.ycombinator.com/item?id=demo", author: "founder_rev", date: "2026-06-02", title: "CRM data is fragmented", body: "We use HubSpot plus Stripe plus Metabase plus Zapier just to answer basic ARR questions. The worst part is copying CSVs around before board meetings.", product: "HubSpot", engagement: 31, ingestedAt: "2026-06-05T10:02:00Z" },
  { id: "notes-1", projectId: "demo-ai-notes", source: "youtube", sourceUrl: "https://youtube.com/watch?v=demo", author: "cs_manager", date: "2026-05-20", title: "AI notes miss account context", body: "Fireflies transcripts are fine, but we still paste account notes into Notion because the AI summaries miss renewal risks and action owners.", product: "Fireflies", engagement: 21, ingestedAt: "2026-06-05T10:03:00Z" },
  { id: "pmm-1", projectId: "demo-pmm-tools", source: "product_hunt", sourceUrl: "https://producthunt.com/posts/demo", author: "solo_pmm", date: "2026-05-22", title: "Launch planning stack is a mess", body: "I wish there was one place to connect Gong snippets, win-loss notes, messaging docs, and launch checklists. Right now I glue Airtable, Docs, and Slack together manually.", product: "Airtable", engagement: 35, ingestedAt: "2026-06-05T10:04:00Z" }
];

export const classifications: Classification[] = [
  { recordId: "crm-1", signalType: "workaround", painCategory: "reporting", emotionalIntensity: 4, urgency: 4, persona: "RevOps manager", productArea: "dashboards", workflowStep: "weekly executive reporting", competitorsMentioned: ["HubSpot"], toolsMentioned: ["Google Sheets"], workaroundPresent: true, willingnessToPaySignal: true, summary: "User exports CRM data to Sheets weekly because native dashboards cannot model renewal and expansion views.", quotableLanguage: "I'd pay for something that saved this manual reporting ritual.", confidence: 0.91, why: "Explicit export workaround, recurring cadence, and willingness-to-pay language." },
  { recordId: "crm-2", signalType: "alternative_request", painCategory: "reporting", emotionalIntensity: 4, urgency: 4, persona: "RevOps manager", productArea: "pipeline reporting", workflowStep: "monthly leadership reporting", competitorsMentioned: ["Salesforce"], toolsMentioned: ["spreadsheets"], workaroundPresent: true, willingnessToPaySignal: false, summary: "User seeks an alternative to Salesforce reports because reporting requires admins and spreadsheet exports.", quotableLanguage: "doesn't require 3 admins and a pile of spreadsheet exports", confidence: 0.87, why: "Alternative-seeking language plus stack/admin burden indicates switching trigger." },
  { recordId: "crm-3", signalType: "stack_fragmentation", painCategory: "revenue intelligence", emotionalIntensity: 3, urgency: 5, persona: "Founder / RevOps", productArea: "ARR reporting", workflowStep: "board meeting prep", competitorsMentioned: ["HubSpot", "Stripe", "Metabase", "Zapier"], toolsMentioned: ["CSV", "Metabase", "Zapier"], workaroundPresent: true, willingnessToPaySignal: true, summary: "Team stitches multiple tools and CSVs together before board meetings to answer ARR questions.", quotableLanguage: "copying CSVs around before board meetings", confidence: 0.89, why: "High-value board workflow with fragmented stack and manual CSV behavior." }
];

export const clusters: Cluster[] = [{ id: "cluster-crm-reporting", projectId: "demo-crm-reporting", name: "Manual CRM-to-spreadsheet revenue reporting", description: "RevOps teams export CRM, billing, and BI data into spreadsheets for leadership-ready revenue views that native CRM dashboards cannot handle.", recordIds: ["crm-1", "crm-2", "crm-3"], representativeQuotes: classifications.map(c => c.quotableLanguage), frequency: 3, sourceMix: { csv: 1, reddit: 1, hacker_news: 1 }, personas: ["RevOps manager", "Founder / RevOps"], productsMentioned: ["HubSpot", "Salesforce", "Stripe", "Metabase", "Zapier"], emotionalIntensity: 3.7, opportunityScore: 87, evidenceStrength: 82, recommendedProductWedge: "Opinionated revenue reporting layer that connects CRM + billing, ships board-ready templates, and removes spreadsheet exports.", recommendedPmmAngle: "Position against CRM dashboard complexity: 'board-ready revenue answers without admin tickets or Friday CSV rituals.'" }];

export const opportunities: Opportunity[] = [{ id: "opp-crm-reporting", projectId: "demo-crm-reporting", clusterId: "cluster-crm-reporting", title: "Board-ready CRM revenue reporting copilot", targetUser: "RevOps managers and SaaS founders preparing weekly exec or board revenue updates", problemStatement: "Native CRM dashboards do not combine renewals, expansion, billing, and segment views cleanly, forcing high-value operators into recurring spreadsheet workarounds.", existingAlternatives: ["CRM dashboards", "BI tools", "Sheets templates", "RevOps consultants"], whyCurrentToolsFail: "They are too generic, require admins or analysts, and do not ship opinionated SaaS revenue workflows out of the box.", mvpScope: ["HubSpot/Salesforce CSV import", "Stripe import", "ARR/pipeline templates", "Board export", "Source-linked anomaly notes"], willingnessToPayHypothesis: "Users who already pay with Friday labor and board-prep risk will pay $99-$499/month to remove recurring reporting toil.", pricingHypothesis: "$149/month self-serve for founders; $499/month team plan with CRM connectors; consulting setup add-on.", distributionChannels: ["RevOps Reddit/community posts", "HubSpot/Salesforce reporting SEO", "board deck template lead magnet", "PMM/RevOps consultant partnerships"], validationPlan: ["Interview 10 RevOps managers using Sheets exports", "Offer concierge CSV-to-board-report service", "Test landing page around 'Friday CSV ritual'", "Measure repeat weekly usage"], risks: ["CRM API complexity", "Crowded BI category", "Trust required for revenue data"], moatPossibilities: ["Template library", "Benchmark dataset", "workflow-specific connectors", "consultant channel"], whyNow: "AI can summarize anomalies and explain revenue changes while APIs/exports make lightweight data assembly feasible.", consultingRelevance: "For PMM clients, this cluster reveals positioning whitespace against CRM dashboard complexity and campaign angles around manual board prep.", buildRecommendation: "validate_first", score: 87, evidenceRecordIds: ["crm-1", "crm-2", "crm-3"] }];
